config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home', as: "home"
    get 'static_pages/help', as:"help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get 'password_resets/new'
    get 'password_resets/edit'

    resources :user_courses
    resources :reviews
    resources :courses
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :users
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.status == "Started"
      @course.started_at = Time.zone.now
    end
    if @course.save
      flash[:success] = t(:course_registered)
      redirect_to @course
    else
      flash[:danger] = t(:course_failed)
      render :new
    end
  end

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find_by(id: params[:id])
    @user_course = UserCourse.new
    @review = Review.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  def update
    @course = Course.find(params[:id])
    if @course.status == "Started"
      @course.started_at = Time.zone.now
    end
    if @course.update(course_params)
      flash[:success] = t(:course_updated)
      redirect_to @course
    else
      flash[:danger] = t(:updated_failed)
      redirect_to courses_path
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :total_month, :total_member, :status, :started_at)
  end

end

app/views/courses/edit.html.erb
<% if current_user.admin %>
  <h1>Update course</h1>
  <html>
    <body>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with model: @course do |f| %>

            <%= f.label :name, t(:course_name) %>
            <%= f.text_field :name, class: "form-control" %>

            <%= f.label :description, t(:course_description) %>
            <%= f.text_field :description, class: "form-control" %>

            <%= f.label :total_month, t(:course_totalmonth) %>
            <%= f.number_field :total_month, class: "form-control" %>


            <%= f.label :status, t(:course_status) %>
            <%= f.select :status, ["Opening", "Started","Finished"] %>

            <%= f.submit "Update", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </body>
  </html>
<% else %>
  <h3><%= t(:not_admin) %></h3>
<% end %>

app/views/courses/index.html.erb
<h1><%= t(:courses_available) %></h1>

<ul>
  <% @courses.each do |course| %>
      <% if current_user&.admin? %>
        <b><mark><em><%= link_to course.name, course %></b></em></mark>
        <% if course.status == "Opening" %>
          | <%= link_to t(:delete), course, method: :delete, data: {confirm: t(:sure)} %>
        <% end %>
        | <%= link_to t(:update), edit_course_path(course) %>

      <% else %>
        <b><mark><em><%= link_to course.name, course %></b></em></mark>
      <% end %>
      <br>
    <p>
      <b><%= t(:description) %></b> <%= course.description %><br>
      <% if course.status == t(:started) %>
        <b><%= t(:started_at) %></b>
        <%= course.started_at %><br>
      <% end %>
      <b><%= t(:total_month) %></b> <%= course.total_month %><br>
      <b><%= t(:total_member) %></b><%= course.user_courses.Approved.count %><br>
      <b><%= t(:status) %></b>
      <% if course.status == "Finished" %>
        <b style="color:red"><%= course.status %></b>
      <% elsif course.status == "Started" %>
        <b style="color:grey"><%= course.status %></b>
      <% else %>
        <b style="color:green"><%= course.status %></b>
      <% end %>
    </p>
  <% end %>
</ul>

app/views/courses/new.html.erb
<% if current_user.admin %>
  <h1><%= t(:add_course) %></h1>
  <html>
    <head>
      <h2><%= t(:course_registration_system) %></h2>
    </head>
    <body>
      <h3><%= t(:adding_course) %></h3>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for :course, url: courses_path do |f| %>

            <%= f.label :name, t(:course_name) %>
            <%= f.text_field :name, class: "form-control" %>

            <%= f.label :description, t(:course_description) %>
            <%= f.text_field :description, class: "form-control" %>

            <%= f.label :total_month, t(:course_totalmonth) %>
            <%= f.number_field :total_month, class: "form-control" %>

            <%= f.label :total_member, t(:course_totalmember) %>
            <%= f.number_field :total_member, class: "form-control" %>

            <%= f.label :status, t(:course_status) %>
            <%= f.number_field :status, class: "form-control" %>

            <%= f.submit "Create course", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </body>
  </html>
<% else %>
  <h3>You are not the admin user!</h3>
<% end %>

app/views/courses/show.html.erb
<h1>Course's title: <%= @course.name %></h1>
<% if current_user&.admin? %>
  <% if @course.status == t(:opening) %>
    <small><%= link_to t(:delete), @course, method: :delete, data: {confirm:  t(:sure)} %> | </small>
  <% end %>
   <small><%= link_to t(:update), edit_course_path(@course) %></small>
<% end %>

<p>
  <b><%= t(:description) %></b> <%= @course.description %><br>
  <% if @course.status == t(:started) %>
    <b><%= t(:started_at) %></b>
    <%= @course.started_at %></br>
  <% end %>
  <b><%= t(:total_month) %></b><%= @course.total_month %><br>
  <b><%= t(:total_member) %></b><%= @course.user_courses.Approved.count %><br>
  <b><%= t(:status) %></b>
  <% if @course.status == "Finished" %>
    <b style="color:red"><%= @course.status %></b>
  <% elsif @course.status == "Started" %>
    <b style="color:grey"><%= @course.status %></b>
  <% else %>
    <b style="color:green"><%= @course.status %></b>
  <% end %>
</p>

<% if !current_user.admin %>
  <%= form_for @user_course do |f| %>
    <% if @course.status == "Opening" %>
      <%= f.hidden_field :user_id, :value => current_user.id %><br>
      <%= f.hidden_field :course_id, :value => @course.id %><br>
      <button name="button" type="submit"><%= t(:register) %></button>
    <% elsif @course.status == "Started" %>
      <%= f.hidden_field :user_id, :value => current_user.id %><br>
      <%= f.hidden_field :course_id, :value => @course.id %><br>
      <button name="button" type="submit"><%= t(:appeal) %></button>
    <% end %>
  <% end %>
<% end %>

<h2><%= t(:student_review) %></h2>
<%= @course.reviews.each do |r| %>
  <%= t(:_name) %><%= r.user.name %><br>
  <%= t(:content) %><%= r.content %>
  <% if current_user.admin %>
    | <%= link_to t(:delete), r, method: :delete, data: {confirm: t(:sure)} %><br><br>
  <% else %>
    <% if current_user.id == r.user_id %>
      | <%= link_to t(:delete), r, method: :delete, data: {confirm: t(:sure)} %>
      | <%= link_to t(:edit), edit_review_path(r) %><br><br>
    <% else %>
      <br><br>
    <% end %>
  <% end %>
<% end %>

<% if !current_user.admin %>
  <strong><h3><%= t(:review_course) %></h3><br></strong>
  <%= form_for @review do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :course_id, :value => @course.id %>
    <%= f.label :content, t(:content) %><br>
    <%= f.text_area :content, class: "form-control" %><br>
    <%= f.submit t(:create_review), class: "btn btn-primary" %>
  <% end %>
<% end %>