config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home', as: "home"
    get 'static_pages/help', as:"help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get 'password_resets/new'
    get 'password_resets/edit'

    resources :user_courses
    resources :reviews
    resources :courses
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :users
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(:c_r), "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(:home), home_path %></li>
        <% if current_user&.admin? %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %><%= t(:_course) %> <b class= "caret"></b></a><% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(:add_course), new_course_path %></li>
              <li class="divider"></li>
              <li> <%= link_to t(:course_offered), courses_path %></li>
            </ul>
        <% else %>
          <li><%= link_to t(:help), help_path %></li>
          <li> <%= link_to t(:course_offered), courses_path %></li>
        <% end %>
        <% if logged_in? %>
          <% if current_user.admin %>
            <li><%= link_to t(:users), users_path %></li>
          <% end %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %><%= t(:account) %> <b class= "caret"></b></a><% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(:profile), current_user %></li>
              <li><%= link_to t(:settings), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t(:log_out), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:log_in), login_path %></li>
        <% end %>
        <li><%= link_to "English", locale: :en %></li>
        <li><%= link_to t(:ja), locale: :jp %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navigation_links.html.erb
<%= content_tag :li do %>
  <%= link_to 'Switch to English', locale:en %>
<%= end unless current_page?(locale:en) %>

<%= content_tag :li do %>
  <%= link_to 'Switch to Japanese', locale:jp %>
<%= end unless current_page?(locale:jp) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>